@startuml
title Online Book Reading System

interface Book {

}

abstract class BookImpl {
    # title: String
    # pages: int
    # author: List<Author>
    # pages: List<Page>
}

class Page {
    - content: String
    - pageNo: int
}

class Author {
    - name: String
}

class EBook {
    - digitalizedBy: User
}

'Rename to Account
interface Person {
}

abstract class User{
    # name: String
}

class Admin {

}

class Librarian{

}

class Reader{
    - membership: Membership
}

class Membership {
    - type: MembershipType
    - expiryDate: Date
}

enum MembershipType {
    STANDARD
    PREMIUM
}


'Book Relationship
Book <|-- BookImpl: implements
Book <|-- EBook: type of
Book "1" *-- "*" Page: contains
Book "*" o-- "*" Author: authored by

'User Relationship
Person <|-- User: type of
User <|-- Reader: type of
User <|-- Admin: type of
User <|-- Librarian: type of
Reader "*" o-- "1" Membership: has


/'
Library Service
'/
package onlinebookreadingsystem.library {
    interface Library {
        addBook(librarian: Librarian, book: Book): void
        removeBook(librarian: Librarian, bookName: String): void
        searchBook(name: String): Optional<Book>
    }

    class LibraryImpl {
        # books: List<Book>
        # librarians: List<Librarian>
        # searchBook: SearchBookStrategy
        # bookListIterator: BookListIterator

        addBook(librarian, book)
        removeBook(librarian, bookName)
        searchBook(name):
    }

    interface SearchBookStrategy<T> {
        search(<T>): List<Book>
    }

    class SearchBookByNameStrategy<String> {
        - books: List<Book>
        search(String name): List<Book>
    }

    interface BookListIterator {
        has();
        getNext();
    }

    class BookListIteratorImpl {
        - bookList: List<Book>

        + has(): boolean
        + getNext(): Book
    }

    Library <|-- LibraryImpl: extends
    Library *-- Book: contains
    Library o-- Librarian: has
    Library o-- SearchBookStrategy: has
    'Search
    SearchBookStrategy <|-- SearchBookByNameStrategy: type of
    'Iterator
    BookListIterator <|-- BookListIteratorImpl: type of
    Library "1" *-- "*" BookListIterator: contains

}

'User Service
package onlinebookreadingsystem.user {
    interface UserManagement {
        addReader(reader: Reader): void
        removeReader(readerName: String): void
        readerLogin(name: String): boolean
        readerLogout(): boolean
        librarianLogin(name: String): boolean
        librarianLogout(): void
        getActiveReader(): Reader
        getActiveLibrarian: Librarian
    }

    class UserManagementImpl {
        - readers: List<Reader>
        - librarians: List<Librarian>
        - admin: Admin
        - activeUser: Reader
        - activeLibrarian: Librarian

        + addReader(reader: Reader)
        + removeReader(readerName: String)
        + readerLogin(name: String): boolean
        + readerLogout(): boolean
        + librarianLogin(name: String): boolean
        + librarianLogout()
        + getActiveReader(): Reader
        + getActiveLibrarian: Librarian
    }

    UserManagement <|-- UserManagementImpl: implements
    UserManagement "1" o-- "*" Reader: contains
    UserManagement "1" o-- "*" Librarian: contains
    UserManagement "1" o-- "1" Admin: contains
}

package onlinebookreadingsystem.bookDisplay {
    interface BookDisplay {
        displayFrontCover()
        displayPage()
        displayEndCover()
        setBook(book: Book)
        nextPage()
        prevPage()
        setPage()

    }

    class BookDisplayImpl {
       - book: Book
       - page: Page
       - renderPage: RenderPage

       + displayFrontCover()
       + displayPage()
       + displayEndCover()
       + setBook(book: Book)
       + nextPage()
       + prevPage()
       + setPage()
    }

    interface RenderPage {

    }

    class RenderPageImpl {
        - page: Page
        - renderStrategy: RenderStrategy


        + setPage(page: Page)
        + render()
    }

    interface RenderStrategy<T> {
        render(page: Page): <T>
    }

    class RenderAsTextStrategy<String> {
        + render(page: Page): String
    }

    BookDisplay <|-- BookDisplayImpl: implements

    RenderStrategy <|-- RenderAsTextStrategy

    BookDisplay "1" o-- "1" Book: has
    BookDisplay "1" o-- "*" RenderPage: has
    RenderPage "1" o-- "*" RenderStrategy: has

    RenderPage <|-- RenderPageImpl: implements
}

interface OnlineBookReadingSystem {
}

class OnlineBookReadingSystemImpl {
    - userManagement: UserManagement
    - library: Library
    - bookDisplay: BookDisplay

}

OnlineBookReadingSystem <|-- OnlineBookReadingSystemImpl: implements
OnlineBookReadingSystem "1" *-- "1" UserManagement: contains
OnlineBookReadingSystem "1" *-- "1" Library: contains
OnlineBookReadingSystem "1" *-- "1" BookDisplay: contains

'Reivew Comments
/'
List of Authors => done
Reader to Membership should be many to 1 => done

interface required for services => done

User management should have users as Aggregation => done
Readerlogout returns boolean(for success/failure) => done

Generic UserManagement => will try in another system

Render page can be interface and can have DI => done
Book should be abstracted -> interface and baseClass
'/

@enduml